language: python

python:
  - "3.6"

services:
  - postgresql

install:
  - pip install -r requirements.txt
  - pip install coveralls
  
script:
  - pytest --with-coverage --cover-package=app  && coverage report
  
after_success:
  - coveralls

notifications:
  email: false
  